<?php

//

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.moodle.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['admindirname'] = 'Dorsièr d\'administracion';
$string['availablelangs'] = 'Paquetatges de lenga disponibles';
$string['chooselanguagehead'] = 'Causissètz una lenga';
$string['cliinstallheader'] = 'Programa d\'installacion de Moodle {$a} en linha de comanda';
$string['databasehost'] = 'Servidor de banca de donadas';
$string['databasename'] = 'Nom de la banca de donadas';
$string['databasetypehead'] = 'Seleccionar un pilòt de banca de donadas';
$string['dataroot'] = 'Dorsièr de donadas';
$string['dbprefix'] = 'Prefix de las taulas';
$string['dirroot'] = 'Dorsièr Moodle';
$string['environmenthead'] = 'Verificacion de l\'environament...';
$string['errorsinenvironment'] = 'Fracàs de la verificacion de l\'environament !';
$string['installation'] = 'Installacion';
$string['paths'] = 'Camins';
$string['pathserrcreatedataroot'] = 'Lo dorsièr de donadas ({$a->dataroot}) pòt pas èsser creat per l\'installador.';
$string['pathshead'] = 'Confirmar los camins d\'accès';
$string['pathsrodataroot'] = 'Lo dorsièr de donadas es pas accessible en escritura.';
$string['pathsunsecuredataroot'] = 'L\'emplaçament del dorsièr de donadas es pas segur';
$string['pathswrongadmindir'] = 'Lo dorsièr d\'administracion existís pas';
$string['phpextension'] = 'Extension PHP {$a}';
$string['phpversion'] = 'Version de PHP';
$string['welcomep10'] = '{$a->installername} ({$a->installerversion})';
$string['wwwroot'] = 'Adreça web';
