<?php

//

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.moodle.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Hindi makalikha ng lang bgsk.';
$string['cannotcreatetempdir'] = 'Hindi makalikha ng temp bgsk.';
$string['cannotdownloadcomponents'] = 'Hindi mai-download ang mga sangkap';
$string['cannotdownloadzipfile'] = 'Hindi mai-download ang ZIP file.';
$string['cannotfindcomponent'] = 'Hindi makita ang component.';
$string['cannotsavemd5file'] = 'Hindi mai-save ang file na md5.';
$string['cannotsavezipfile'] = 'Hindi mai-save ang file na ZIP.';
$string['cannotunzipfile'] = 'Hindi mai-unzip ang file.';
$string['componentisuptodate'] = 'Up-to-date ang component.';
$string['downloadedfilecheckfailed'] = 'Bigo ang  pagsusuri  sa idinownload na file.';
$string['invalidmd5'] = 'Mali ang check variable - paki-ulit';
$string['missingrequiredfield'] = 'May ilang nawawalang field na kailangan';
$string['wrongdestpath'] = 'Mali ang patutunguhang landas';
$string['wrongsourcebase'] = 'Mali ang URL base ng source.';
$string['wrongzipfilename'] = 'Mali ang pangalan ng ZIP file';
