<?php

//

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.moodle.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['clianswerno'] = 'n';
$string['cliansweryes'] = 's';
$string['cliincorrectvalueerror'] = 'Error, valor incorrecta  "{$a->value}" pa "{$a->option}"';
$string['cliincorrectvalueretry'] = 'Valor incorrecta, per favor, intente de nuevo';
$string['clitypevalue'] = 'valor d\'o tipo';
$string['clitypevaluedefault'] = 'valor d\'o tipo, prete Enter pa utilizar la valor per defecto ({$a})';
$string['cliunknowoption'] = 'Opcions no reconoixidas:
{$a}
Per favor, utilice la opción Aduya.';
$string['cliyesnoprompt'] = 'escriba s (pa sí) u n (pa no)';
$string['environmentrequireinstall'] = 'ha d\'estar instalau/activau';
$string['environmentrequireversion'] = 'versión {$a->needed} ye obligatoria y ye executando {$a->current}';
$string['upgradekeyset'] = 'Clau d\'actualización (deixar en blanco pa no establir-la)';
